// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Supabase: Use DIRECT connection for migrations (not pooling)
    // For runtime, use DATABASE_URL with pooling in your app
    // If DIRECT_URL is set, use it for migrations; otherwise use DATABASE_URL
    url: process.env.DIRECT_URL 
      ? process.env.DIRECT_URL 
      : env("DATABASE_URL"),
  },
});
